# Generated by Django 3.2.4 on 2021-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_model',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notes_model',
            name='username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
