# Generated by Django 3.2.6 on 2021-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_by_user_usernotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes_by_user',
            old_name='uuid',
            new_name='id',
        ),
    ]
