# Generated by Django 3.2.4 on 2021-06-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210618_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes_by_user',
            name='username',
        ),
        migrations.AddField(
            model_name='notes_by_user',
            name='notesuser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notess', to='notes.notes_user'),
        ),
    ]
