# Generated by Django 3.2.4 on 2021-06-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_notes_by_user_notesuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_by_user',
            name='notesuser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notess', to='notes.notes_user'),
        ),
    ]
