# Generated by Django 3.2.4 on 2021-06-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_user_model_id'),
        ('notes', '0006_notes_by_user_notesuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes_by_user',
            name='notesuser',
        ),
        migrations.AddField(
            model_name='notes_by_user',
            name='userNotes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notess', to='userdata.user_model'),
        ),
        migrations.DeleteModel(
            name='notes_user',
        ),
    ]
