# Generated by Django 3.2.4 on 2021-07-19 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_auto_20210630_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_by_user',
            name='userNotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
