# Generated by Django 3.2.6 on 2021-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notes_by_user_usernotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_by_user',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
