# Generated by Django 3.2.6 on 2021-08-21 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_notes_by_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes_by_user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
