# Generated by Django 3.2.6 on 2021-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='uuid',
            new_name='id',
        ),
    ]
