# Generated by Django 3.2.6 on 2021-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='password',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
