# Generated by Django 3.2.4 on 2021-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_user_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
