# Generated by Django 3.2.4 on 2021-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_alter_user_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
