# Generated by Django 3.2.4 on 2021-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_alter_user_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='password',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
